### ISSUE TITLE
Are we going to support apple silicon?

### ISSUE THREAD

**Issue by eezlin** [leavesgrp/COPT-MATLAB#3]
Matlab2023b supports apple silicon natively, but cannot install copt-matlab and runs as follows:

>> coptmex_install
error using coptmex_install
Unsupported operating system MACA64

**Comment by riis-hhd** [comment]
We've released new version, which should support apple silicon. Please let us know.

**Comment by eezlin** [comment]
Hello, I followed the installation and found that I still have problems. Maybe it's missing some "*.dylib" to work.
The following error is reported:

>> coptmex_install
Installing MATLAB interface for Cardinal Optimizer on MacOSX (arm64) system...
Add and save path /Users/myname/Documents/MATLAB/copt-matlab/lib to MATLAB search path.
MEX File '/Users/myname/Documents/MATLAB/copt-matlab/lib/copt_solve.mexmaca64' is invalid:
dlopen(/Users/myname/Documents/MATLAB/copt-matlab/lib/copt_solve.mexmaca64, 0x0006): Library not loaded: @rpath/libcopt.dylib
  Referenced from: <67BCA23C-2E0D-3ED7-9E8C-98C6DA8BFC73> /Users/myname/Documents/MATLAB/copt-matlab/lib/copt_solve.mexmaca64
  Reason: tried: '/Users/myname/Documents/MATLAB/copt-matlab/lib/libcopt.dylib' (no such file),
  '/Users/myname/Documents/MATLAB/copt-matlab/lib/../lib/libcopt.dylib' (no such file),
  '/Users/myname/Documents/MATLAB/copt-matlab/lib/libcopt.dylib' (no such file),
  '/Users/myname/Documents/MATLAB/copt-matlab/lib/../lib/libcopt.dylib' (no such file),
  '/Applications/MATLAB_R2023b.app/bin/maca64/libcopt.dylib' (no such file),
  '/Applications/MATLAB_R2023b.app/bin/maca64/./libcopt.dylib' (no such file),
  '/Applications/MATLAB_R2023b.app/bin/maca64/../../sys/os/maca64/libcopt.dylib' (no such file),
  '/Applications/MATLAB_R2023b.app/Contents/MacOS/libcopt.dylib' (no such file),
  '/Applications/MATLAB_R2023b.app/Contents/MacOS/./libcopt.dylib' (no such file),
  '/Applications/MATLAB_R2023b.app/Contents/MacOS/../../standalone/bin/maca64/libcopt.dylib' (no such file),
  '/Applications/MATLAB_R2023b.app/Contents/MacOS/../../sys/os/maca64/libcopt.dylib' (no such file),
  '/Applications/MATLAB_R2023b.app/bin/maca64/libcopt.dylib' (no such file), '/usr/local/lib/libcopt.dylib' (no such file),
  '/usr/lib/libcopt.dylib' (no such file, not in dyld cache)

**Comment by riis-hhd** [comment]
copt-matlab release package requires users have COPT installed. Please visit https://www.shanshu.ai/copt for free trial.

The above error shows missing libcopt.dylib, which is core lib of COPT.

**Comment by eezlin** [comment]
Thank you about your answer. But it doesn't work like it did before. I have been using COPT and your plugin on windows 
 and MACI64 MATLAB before.
It is my .zsh file and my copt_cmd works in the terminal.
# COTP 
export COPT_HOME=/Applications/copt70
export COPT_LICENSE_DIR=/Applications/copt70
export PATH=$COPT_HOME/bin:$PATH
export DYLD_LIBRARY_PATH=$COPT_HOME/lib:$DYLD_LIBRARY_PATH
# COPT END

Last login: Tue Oct 24 12:38:50 on ttys000
(base) myname@MacBook-Air ~ % copt_cmd 
Cardinal Optimizer v7.0.2. Build date Oct 16 2023
Copyright Cardinal Operations 2023. All Rights Reserved
COPT>

**Comment by riis-hhd** [comment]
Thanks for your feedback. We are working on it. 
As of now, please use the following workaround:
1. copy libcopt.dylib from /Applications/copt70/lib/ to copt-matlab/lib
2. run "xattr -dr com.apple.quarantine copt-matlab/" for mac security check
3. install again (run coptmex_install)

**Comment by eezlin** [comment]
It works. By the way, this is a very exciting plugin, thank you.
